In [2]:
import numpy as np

a = np.array([[1,2],
     [3,4],
     [5,6]])
print(a.shape)

(3, 2)


In [3]:
b = np.array([[2,1,3],
             [1,1,1]])
print(b.shape)

(2, 3)


In [27]:
my_dot = np.dot(a, b)
print(my_dot.shape)

(3, 3)


In [28]:
my_dot = np.dot(a.T, b.T)
print(my_dot.shape)

(2, 2)


In [29]:
my_dot = np.dot(a.T, b)
print(my_dot.shape)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [30]:
my_dot = np.dot(a, b.T)
print(my_dot.shape)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [4]:
a * b.T

array([[ 2,  2],
       [ 3,  4],
       [15,  6]])

In [5]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
b.T


array([[2, 1],
       [1, 1],
       [3, 1]])