These are tips from [python tutorial](http://cs231n.github.io/python-numpy-tutorial/), or accessible in my [Google Keep](https://keep.google.com/#NOTE/1486329851134.101677520.fce)

## Working with numpy arrays

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays

### Integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [17]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
c= a[[0, 1, 2], [0, 1, 0]]
print(c)  # Prints "[1 4 5]"
print(type(c))
print(c.shape)

[1 4 5]
<class 'numpy.ndarray'>
(3,)


Similarly, can reference the array thus:

In [16]:
d = np.array([a[0,0], a[1,1], a[2,0]])
print(d)  # Prints "[1 4 5]"
print(type(d))
print(d.shape)

[1 4 5]
<class 'numpy.ndarray'>
(3,)


Compare with creating a list from an array:

In [15]:
b = [a[0,0], a[1,1], a[2,0]]
print(b)
print(type(b))
print(len(b))

[1, 4, 5]
<class 'list'>
3


In [28]:
import numpy as np

# Create a new array from which we will select elements
z = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
# Create an array of indices
y = np.array([0, 2, 0, 1])
print (y)

[0 2 0 1]


In [30]:
# Select one element from each row of a using the indices in b
print (z[np.arange(4), y])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [31]:
# Mutate one element from each row of a using the indices in b
z[np.arange(4), y] += 10
print(z)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
